### ISSUE TITLE
Problem generating visualization with sample data

### ISSUE THREAD

**Issue by rharige** [StanfordHCI/termite#3]
I am running into this error at the end of processing input file (formatted with `number[tab]text[\n]`):

``` javascript
Iteration no.  74
#-------- breaking out early ---------#
candidates checked:  4
change in energy:  0.0
maxTerm:  
maxPosition:  0
Traceback (most recent call last):
  File "./execute.py", line 164, in <module>
    main()
  File "./execute.py", line 161, in main
    Execute( logging_level ).execute( corpus_format, corpus_path, model_library, model_path, data_path, num_topics, number_of_seriated_terms )
  File "./execute.py", line 89, in execute
    ComputeSeriation( self.logger.level ).execute( data_path, number_of_seriated_terms )
  File "/media/drive/Downloads/termite-master/pipeline/compute_seriation.py", line 56, in execute
    self.compute( numSeriatedTerms )
  File "/media/drive/Downloads/termite-master/pipeline/compute_seriation.py", line 103, in compute
    (candidateTerms, self.seriation.term_ordering, self.seriation.term_iter_index, self.buffers) = self.iterate_eff(candidateTerms, self.seriation.term_ordering, self.seriation.term_iter_index, self.buffers, self.bestEnergies, iteration)
  File "/media/drive/Downloads/termite-master/pipeline/compute_seriation.py", line 205, in iterate_eff
    candidateTerms.remove(maxTerm)
ValueError: list.remove(x): x not in list
```

Input data file: http://db.tt/XYfTQDzG
Complete console log: http://db.tt/19rTChaM

@jcchuang - I would appreciate any help to get Termite running without any issues! Thanks.

**Comment by jcchuang** [comment]
I am currently working on version 2, with a revamped seriation code, and so don't have the time to examine this issue in depth.  One possibility, given there are only 19 sentences in the corpus, is that the seriation algorithm ran out of available vocabulary after the 74th iteration...
